name: build
on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
          21,
        ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          dependency-graph: generate-and-submit
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew build
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/